version: '3.9'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: kafka_zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./kafka_cluster/zookeeper/data:/data
      - ./kafka_cluster/zookeeper/datalog:/datalog
      - ./kafka_cluster/zookeeper/logs:/logs
    restart: always
    networks:
      video-service:
    network_mode: bridge
  kafka1:
    image: wurstmeister/kafka
    depends_on:
      - kafka_zookeeper
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_ZOOKEEPER_CONNECT: 192.168.2.105:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.105:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - ./kafka_cluster/broker1/logs:/opt/kafka/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    network_mode: bridge
    networks:
      video-service:
  kafka2:
    image: wurstmeister/kafka
    depends_on:
      - kafka_zookeeper
    container_name: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_ZOOKEEPER_CONNECT: 192.168.2.105:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.105:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
    volumes:
      - ./kafka_cluster/broker2/logs:/opt/kafka/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    network_mode: bridge
    networks:
      video-service:
  kafka3:
    image: wurstmeister/kafka
    depends_on:
      - kafka_zookeeper
    container_name: kafka3
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_ZOOKEEPER_CONNECT: 192.168.2.105:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.105:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
    volumes:
      - ./kafka_cluster/broker3/logs:/opt/kafka/logs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    network_mode: bridge
    networks:
      video-service:
  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    restart: always
    network_mode: bridge
    networks:
      video-service:
    depends_on:
      - kafka_zookeeper
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: 192.168.2.105:2181
networks:
  video-service:
    external: true